export const staticData: {
  railway: {[key: string]: string},
  operator: {[key: string]: string},
  trainType: {[railway: string]: {[type: string]: string}},
  station: {[key: string]: {code?: string, name: string}},
  station_order: {[key: string]: string[]},
} = {
  railway: {
    "Toei.Asakusa": "都営浅草線",
    "Toei.Oedo": "都営大江戸線",
    "Toei.Shinjuku": "都営新宿線",
    "Toei.Mita": "都営三田線",
    "Keio.Keio": "京王線",
    "Keio.Sagamihara": "京王相模原線",
    "Keio.KeioNew": "京王新線",
    "Keisei.Main": "京成本線",
    "Keisei.Oshiage": "京成押上線",
    "Keisei.NaritaSkyAccess": "京成成田スカイアクセス線",
    "Hokuso.Hokuso": "北総線",
    "Keikyu.Main": "京急本線",
    "Keikyu.Airport": "京急空港線",
    "Keikyu.Kurihama": "京急久里浜線",
    "Tobu.TobuSkytree": "東武スカイツリーライン",
    "Tobu.TobuSkytreeBranch": "東武スカイツリーライン（押上支線）",
    "TokyoMetro.Ginza": "東京メトロ銀座線",
    "TokyoMetro.Tozai": "東京メトロ東西線",
    "TokyoMetro.Hibiya": "東京メトロ日比谷線",
    "TokyoMetro.Hanzomon": "東京メトロ半蔵門線",
    "JR-East.Yamanote": "JR山手線",
    "JR-East.KeihinTohokuNegishi": "JR京浜東北線・根岸線",
    "JR-East.SobuRapid": "JR総武快速線",
    "JR-East.JobanRapid": "JR常磐線快速電車",
    "JR-East.Tokaido": "JR東海道線",
    "JR-East.Yokosuka": "JR横須賀線",
    "JR-East.ChuoSobuLocal": "JR中央・総武線各駅停車",
    "Yurikamome.Yurikamome": "ゆりかもめ線",
    "TokyoMonorail.HanedaAirport": "東京モノレール羽田空港線",
    "Tokyu.Ikegami": "東急池上線",
  },
  operator: {
    "Toei": "東京都交通局",
    "TokyoMetro": "東京メトロ",
    "Keio": "京王電鉄",
    "Keisei": "京成電鉄",
    "Hokuso": "北総鉄道",
    "Keikyu": "京浜急行電鉄",
    "JR-East": "東日本旅客鉄道株式会社",
    "Yurikamome": "ゆりかもめ",
    "TokyoMonorail": "東京モノレール",
    "Tokyu": "東急電鉄",
  },
  trainType: {
    "Toei.Asakusa": {
      "Toei.Local": "普通",
      "Toei.Rapid": "快速",
      "Toei.Express": "急行",
      "Toei.LimitedExpress": "特急",
      "Toei.AccessExpress": "アクセス特急",
      "Toei.RapidLimitedExpress": "快速特急",
      "Toei.AirportRapidLimitedExpress": "エアポート快特",
    },
    "Toei.Shinjuku": {
      "Toei.Local": "各停",
      "Toei.Express": "急行",
    },
  },
  station: {
    "Keikyu.Airport.HanedaAirportTerminal1and2": {
      code: "KK-17",
      name: "羽田空港第1・第2ターミナル",
    },
    "Hokuso.Hokuso.ImbaNihonIdai": {
      code: "HS-14",
      name: "印旛日本医大",
    },
    "Hokuso.Hokuso.InzaiMakinohara": {
      code: "HS-13",
      name: "印西牧の原",
    },
    "Keisei.NaritaSkyAccess.NaritaAirportTerminal1": {
      code: "KS-42",
      name: "成田空港（成田第1ターミナル）",
    },
    "Keisei.Main.NaritaAirportTerminal1": {
      code: "KS-42",
      name: "成田空港（成田第1ターミナル）",
    },
    "Keikyu.Kurihama.Misakiguchi": {
      code: "KK-72",
      name: "三崎口",
    },
    "Keisei.Oshiage.Aoto": {
      code: "KS-09",
      name: "青砥",
    },
    "Keisei.Main.KeiseiTakasago": {
      code: "KS-10",
      name: "京成高砂",
    },
  },
  station_order: {
    "Toei.Asakusa": ["A-01", "A-02", "A-03", "A-04", "A-05", "A-06", "A-07", "A-08", "A-09", "A-10", "A-11", "A-12", "A-13", "A-14", "A-15", "A-16", "A-17", "A-18", "A-19", "A-20"],
    "Toei.Shinjuku": ["S-01", "S-02", "S-03", "S-04", "S-05", "S-06", "S-07", "S-08", "S-09", "S-10", "S-11", "S-12", "S-13", "S-14", "S-15", "S-16", "S-17", "S-18", "S-19", "S-20", "S-21"],
  }
}
